#version 430 core

layout(local_size_x = 16) in;

layout(std430, binding = 9) buffer BinOffsets { uint binOffsets[]; };

shared uint temp[16];

void main()
{
    uint t = gl_LocalInvocationID.x;
    uint myTotal = binOffsets[t];
    temp[t] = myTotal;
    barrier();

    for (uint offset = 1u; offset < 16u; offset <<= 1u)
    {
        uint prev = (t >= offset) ? temp[t - offset] : 0u;
        barrier();
        temp[t] += prev;
        barrier();
    }

    uint exclusive = temp[t] - myTotal;
    binOffsets[t] = exclusive;
}
