#version 430 core

layout(local_size_x = 256) in;

layout(std430, binding = 1) writeonly buffer IndexBufferA      { uint idsA[]; };
layout(std430, binding = 2) readonly  buffer PreprocBuffer     { vec4 preprocBuffer[]; };
layout(std430, binding = 4) readonly  buffer VisibleIndexBuffer{ uint visibleIndices[]; };
layout(std430, binding = 5) writeonly buffer KeysBufferA       { uint keysA[]; };

uniform uint uVisibleCount;

void main()
{
    uint k = gl_GlobalInvocationID.x;
    if (k >= uVisibleCount) return;

    uint id = visibleIndices[k];
    float tz = preprocBuffer[3u * id + 1u].w;

    idsA[k]  = id;
    keysA[k] = 0xFFFFFFFFu - floatBitsToUint(tz);
}
